import Foundation

/// 词组练习数据（500 常用词组）
/// 数据来源：rime/rime-wubi (LGPL v3)
struct PhraseEntry: Codable {
    let text: String
    let code: String
    let type: Int  // 2=两字词 3=三字词 4=四字及以上
    let hint: String
}

enum PhraseData {
    static let all: [PhraseEntry] = [
        PhraseEntry(text: "网站", code: "mquh", type: 2, hint: "网(MQ) + 站(UH)"),
        PhraseEntry(text: "最新", code: "jbus", type: 2, hint: "最(JB) + 新(US)"),
        PhraseEntry(text: "中国", code: "khlg", type: 2, hint: "中(KH) + 国(LG)"),
        PhraseEntry(text: "商品", code: "umkk", type: 2, hint: "商(UM) + 品(KK)"),
        PhraseEntry(text: "所有", code: "rnde", type: 2, hint: "所(RN) + 有(DE)"),
        PhraseEntry(text: "首页", code: "utdm", type: 2, hint: "首(UT) + 页(DM)"),
        PhraseEntry(text: "市场", code: "ymfn", type: 2, hint: "市(YM) + 场(FN)"),
        PhraseEntry(text: "管理", code: "tpgj", type: 2, hint: "管(TP) + 理(GJ)"),
        PhraseEntry(text: "表示", code: "gefi", type: 2, hint: "表(GE) + 示(FI)"),
        PhraseEntry(text: "时间", code: "jfuj", type: 2, hint: "时(JF) + 间(UJ)"),
        PhraseEntry(text: "可以", code: "skny", type: 2, hint: "可(SK) + 以(NY)"),
        PhraseEntry(text: "中心", code: "khny", type: 2, hint: "中(KH) + 心(NY)"),
        PhraseEntry(text: "日本", code: "jjsg", type: 2, hint: "日(JJ) + 本(SG)"),
        PhraseEntry(text: "内容", code: "mwpw", type: 2, hint: "内(MW) + 容(PW)"),
        PhraseEntry(text: "联系", code: "butx", type: 2, hint: "联(BU) + 系(TX)"),
        PhraseEntry(text: "以上", code: "nyhh", type: 2, hint: "以(NY) + 上(HH)"),
        PhraseEntry(text: "使用", code: "wget", type: 2, hint: "使(WG) + 用(ET)"),
        PhraseEntry(text: "查看", code: "sjrh", type: 2, hint: "查(SJ) + 看(RH)"),
        PhraseEntry(text: "利用", code: "tjet", type: 2, hint: "利(TJ) + 用(ET)"),
        PhraseEntry(text: "自己", code: "thnn", type: 2, hint: "自(TH) + 己(NN)"),
        PhraseEntry(text: "信息", code: "wyth", type: 2, hint: "信(WY) + 息(TH)"),
        PhraseEntry(text: "我们", code: "trwu", type: 2, hint: "我(TR) + 们(WU)"),
        PhraseEntry(text: "生活", code: "tgit", type: 2, hint: "生(TG) + 活(IT)"),
        PhraseEntry(text: "可能", code: "skce", type: 2, hint: "可(SK) + 能(CE)"),
        PhraseEntry(text: "更新", code: "gjus", type: 2, hint: "更(GJ) + 新(US)"),
        PhraseEntry(text: "搜索", code: "rvfp", type: 2, hint: "搜(RV) + 索(FP)"),
        PhraseEntry(text: "提供", code: "rjwa", type: 2, hint: "提(RJ) + 供(WA)"),
        PhraseEntry(text: "方法", code: "yyif", type: 2, hint: "方(YY) + 法(IF)"),
        PhraseEntry(text: "一个", code: "ggwh", type: 2, hint: "一(GG) + 个(WH)"),
        PhraseEntry(text: "公司", code: "wcng", type: 2, hint: "公(WC) + 司(NG)"),
        PhraseEntry(text: "注册", code: "iymm", type: 2, hint: "注(IY) + 册(MM)"),
        PhraseEntry(text: "下载", code: "ghfa", type: 2, hint: "下(GH) + 载(FA)"),
        PhraseEntry(text: "没有", code: "imde", type: 2, hint: "没(IM) + 有(DE)"),
        PhraseEntry(text: "作者", code: "wtft", type: 2, hint: "作(WT) + 者(FT)"),
        PhraseEntry(text: "其他", code: "adwb", type: 2, hint: "其(AD) + 他(WB)"),
        PhraseEntry(text: "世界", code: "anlw", type: 2, hint: "世(AN) + 界(LW)"),
        PhraseEntry(text: "问题", code: "ukjg", type: 2, hint: "问(UK) + 题(JG)"),
        PhraseEntry(text: "相关", code: "shud", type: 2, hint: "相(SH) + 关(UD)"),
        PhraseEntry(text: "就能", code: "yice", type: 2, hint: "就(YI) + 能(CE)"),
        PhraseEntry(text: "图片", code: "ltth", type: 2, hint: "图(LT) + 片(TH)"),
        PhraseEntry(text: "发表", code: "ntge", type: 2, hint: "发(NT) + 表(GE)"),
        PhraseEntry(text: "最近", code: "jbrp", type: 2, hint: "最(JB) + 近(RP)"),
        PhraseEntry(text: "本站", code: "sguh", type: 2, hint: "本(SG) + 站(UH)"),
        PhraseEntry(text: "收藏", code: "nhad", type: 2, hint: "收(NH) + 藏(AD)"),
        PhraseEntry(text: "评论", code: "ygyw", type: 2, hint: "评(YG) + 论(YW)"),
        PhraseEntry(text: "发布", code: "ntdm", type: 2, hint: "发(NT) + 布(DM)"),
        PhraseEntry(text: "挣扎", code: "rqrn", type: 2, hint: "挣(RQ) + 扎(RN)"),
        PhraseEntry(text: "北京", code: "uxyi", type: 2, hint: "北(UX) + 京(YI)"),
        PhraseEntry(text: "关于", code: "udgf", type: 2, hint: "关(UD) + 于(GF)"),
        PhraseEntry(text: "文章", code: "yyuj", type: 2, hint: "文(YY) + 章(UJ)"),
        PhraseEntry(text: "地址", code: "fbfh", type: 2, hint: "地(FB) + 址(FH)"),
        PhraseEntry(text: "服务", code: "ebtl", type: 2, hint: "服(EB) + 务(TL)"),
        PhraseEntry(text: "个人", code: "whww", type: 2, hint: "个(WH) + 人(WW)"),
        PhraseEntry(text: "中文", code: "khyy", type: 2, hint: "中(KH) + 文(YY)"),
        PhraseEntry(text: "近日", code: "rpjj", type: 2, hint: "近(RP) + 日(JJ)"),
        PhraseEntry(text: "追加", code: "wnlk", type: 2, hint: "追(WN) + 加(LK)"),
        PhraseEntry(text: "论坛", code: "ywff", type: 2, hint: "论(YW) + 坛(FF)"),
        PhraseEntry(text: "支持", code: "fcrf", type: 2, hint: "支(FC) + 持(RF)"),
        PhraseEntry(text: "全部", code: "wguk", type: 2, hint: "全(WG) + 部(UK)"),
        PhraseEntry(text: "技术", code: "rfsy", type: 2, hint: "技(RF) + 术(SY)"),
        PhraseEntry(text: "方式", code: "yyaa", type: 2, hint: "方(YY) + 式(AA)"),
        PhraseEntry(text: "有限", code: "debv", type: 2, hint: "有(DE) + 限(BV)"),
        PhraseEntry(text: "位置", code: "wulf", type: 2, hint: "位(WU) + 置(LF)"),
        PhraseEntry(text: "加入", code: "lkty", type: 2, hint: "加(LK) + 入(TY)"),
        PhraseEntry(text: "登录", code: "wgvi", type: 2, hint: "登(WG) + 录(VI)"),
        PhraseEntry(text: "用户", code: "etyn", type: 2, hint: "用(ET) + 户(YN)"),
        PhraseEntry(text: "如果", code: "vkjs", type: 2, hint: "如(VK) + 果(JS)"),
        PhraseEntry(text: "代表", code: "wage", type: 2, hint: "代(WA) + 表(GE)"),
        PhraseEntry(text: "新闻", code: "usub", type: 2, hint: "新(US) + 闻(UB)"),
        PhraseEntry(text: "注意", code: "iyuj", type: 2, hint: "注(IY) + 意(UJ)"),
        PhraseEntry(text: "推荐", code: "rwad", type: 2, hint: "推(RW) + 荐(AD)"),
        PhraseEntry(text: "电话", code: "jnyt", type: 2, hint: "电(JN) + 话(YT)"),
        PhraseEntry(text: "画像", code: "glwq", type: 2, hint: "画(GL) + 像(WQ)"),
        PhraseEntry(text: "工作", code: "aawt", type: 2, hint: "工(AA) + 作(WT)"),
        PhraseEntry(text: "产品", code: "utkk", type: 2, hint: "产(UT) + 品(KK)"),
        PhraseEntry(text: "留言", code: "qyyy", type: 2, hint: "留(QY) + 言(YY)"),
        PhraseEntry(text: "健康", code: "wvyv", type: 2, hint: "健(WV) + 康(YV)"),
        PhraseEntry(text: "点击", code: "hkfm", type: 2, hint: "点(HK) + 击(FM)"),
        PhraseEntry(text: "投稿", code: "rmty", type: 2, hint: "投(RM) + 稿(TY)"),
        PhraseEntry(text: "网络", code: "mqxt", type: 2, hint: "网(MQ) + 络(XT)"),
        PhraseEntry(text: "条件", code: "tswr", type: 2, hint: "条(TS) + 件(WR)"),
        PhraseEntry(text: "知道", code: "tdut", type: 2, hint: "知(TD) + 道(UT)"),
        PhraseEntry(text: "研究", code: "dgpw", type: 2, hint: "研(DG) + 究(PW)"),
        PhraseEntry(text: "版权", code: "thsc", type: 2, hint: "版(TH) + 权(SC)"),
        PhraseEntry(text: "手机", code: "rtsm", type: 2, hint: "手(RT) + 机(SM)"),
        PhraseEntry(text: "以下", code: "nygh", type: 2, hint: "以(NY) + 下(GH)"),
        PhraseEntry(text: "全国", code: "wglg", type: 2, hint: "全(WG) + 国(LG)"),
        PhraseEntry(text: "目前", code: "hhue", type: 2, hint: "目(HH) + 前(UE)"),
        PhraseEntry(text: "什么", code: "wftc", type: 2, hint: "什(WF) + 么(TC)"),
        PhraseEntry(text: "现在", code: "gmdh", type: 2, hint: "现(GM) + 在(DH)"),
        PhraseEntry(text: "好友", code: "vbdc", type: 2, hint: "好(VB) + 友(DC)"),
        PhraseEntry(text: "今日", code: "wyjj", type: 2, hint: "今(WY) + 日(JJ)"),
        PhraseEntry(text: "帮助", code: "dteg", type: 2, hint: "帮(DT) + 助(EG)"),
        PhraseEntry(text: "会员", code: "wfkm", type: 2, hint: "会(WF) + 员(KM)"),
        PhraseEntry(text: "在线", code: "dhxg", type: 2, hint: "在(DH) + 线(XG)"),
        PhraseEntry(text: "一般", code: "ggte", type: 2, hint: "一(GG) + 般(TE)"),
        PhraseEntry(text: "不能", code: "gice", type: 2, hint: "不(GI) + 能(CE)"),
        PhraseEntry(text: "主页", code: "ygdm", type: 2, hint: "主(YG) + 页(DM)"),
        PhraseEntry(text: "回答", code: "lktw", type: 2, hint: "回(LK) + 答(TW)"),
        PhraseEntry(text: "基本", code: "adsg", type: 2, hint: "基(AD) + 本(SG)"),
        PhraseEntry(text: "安全", code: "pvwg", type: 2, hint: "安(PV) + 全(WG)"),
        PhraseEntry(text: "第一", code: "txgg", type: 2, hint: "第(TX) + 一(GG)"),
        PhraseEntry(text: "这个", code: "ypwh", type: 2, hint: "这(YP) + 个(WH)"),
        PhraseEntry(text: "进行", code: "fjtf", type: 2, hint: "进(FJ) + 行(TF)"),
        PhraseEntry(text: "电子", code: "jnbb", type: 2, hint: "电(JN) + 子(BB)"),
        PhraseEntry(text: "朋友", code: "eedc", type: 2, hint: "朋(EE) + 友(DC)"),
        PhraseEntry(text: "必要", code: "ntsv", type: 2, hint: "必(NT) + 要(SV)"),
        PhraseEntry(text: "希望", code: "qdyn", type: 2, hint: "希(QD) + 望(YN)"),
        PhraseEntry(text: "需要", code: "fdsv", type: 2, hint: "需(FD) + 要(SV)"),
        PhraseEntry(text: "重要", code: "tgsv", type: 2, hint: "重(TG) + 要(SV)"),
        PhraseEntry(text: "免费", code: "qkxj", type: 2, hint: "免(QK) + 费(XJ)"),
        PhraseEntry(text: "队长", code: "bwta", type: 2, hint: "队(BW) + 长(TA)"),
        PhraseEntry(text: "分类", code: "wvod", type: 2, hint: "分(WV) + 类(OD)"),
        PhraseEntry(text: "女性", code: "vvnt", type: 2, hint: "女(VV) + 性(NT)"),
        PhraseEntry(text: "系列", code: "txgq", type: 2, hint: "系(TX) + 列(GQ)"),
        PhraseEntry(text: "发展", code: "ntna", type: 2, hint: "发(NT) + 展(NA)"),
        PhraseEntry(text: "空间", code: "pwuj", type: 2, hint: "空(PW) + 间(UJ)"),
        PhraseEntry(text: "合作", code: "wgwt", type: 2, hint: "合(WG) + 作(WT)"),
        PhraseEntry(text: "博客", code: "fgpt", type: 2, hint: "博(FG) + 客(PT)"),
        PhraseEntry(text: "教育", code: "ftyc", type: 2, hint: "教(FT) + 育(YC)"),
        PhraseEntry(text: "最后", code: "jbrg", type: 2, hint: "最(JB) + 后(RG)"),
        PhraseEntry(text: "国际", code: "lgbf", type: 2, hint: "国(LG) + 际(BF)"),
        PhraseEntry(text: "要求", code: "svfi", type: 2, hint: "要(SV) + 求(FI)"),
        PhraseEntry(text: "写真", code: "pgfh", type: 2, hint: "写(PG) + 真(FH)"),
        PhraseEntry(text: "最大", code: "jbdd", type: 2, hint: "最(JB) + 大(DD)"),
        PhraseEntry(text: "难忘", code: "cwyn", type: 2, hint: "难(CW) + 忘(YN)"),
        PhraseEntry(text: "法律", code: "iftv", type: 2, hint: "法(IF) + 律(TV)"),
        PhraseEntry(text: "我的", code: "trrq", type: 2, hint: "我(TR) + 的(RQ)"),
        PhraseEntry(text: "直接", code: "fhru", type: 2, hint: "直(FH) + 接(RU)"),
        PhraseEntry(text: "如何", code: "vkws", type: 2, hint: "如(VK) + 何(WS)"),
        PhraseEntry(text: "主题", code: "ygjg", type: 2, hint: "主(YG) + 题(JG)"),
        PhraseEntry(text: "参考", code: "cdft", type: 2, hint: "参(CD) + 考(FT)"),
        PhraseEntry(text: "已经", code: "nnxc", type: 2, hint: "已(NN) + 经(XC)"),
        PhraseEntry(text: "主要", code: "ygsv", type: 2, hint: "主(YG) + 要(SV)"),
        PhraseEntry(text: "非常", code: "djip", type: 2, hint: "非(DJ) + 常(IP)"),
        PhraseEntry(text: "列表", code: "gqge", type: 2, hint: "列(GQ) + 表(GE)"),
        PhraseEntry(text: "社会", code: "pywf", type: 2, hint: "社(PY) + 会(WF)"),
        PhraseEntry(text: "活动", code: "itfc", type: 2, hint: "活(IT) + 动(FC)"),
        PhraseEntry(text: "企业", code: "whog", type: 2, hint: "企(WH) + 业(OG)"),
        PhraseEntry(text: "任何", code: "wtws", type: 2, hint: "任(WT) + 何(WS)"),
        PhraseEntry(text: "专业", code: "fnog", type: 2, hint: "专(FN) + 业(OG)"),
        PhraseEntry(text: "视频", code: "pyhi", type: 2, hint: "视(PY) + 频(HI)"),
        PhraseEntry(text: "部分", code: "ukwv", type: 2, hint: "部(UK) + 分(WV)"),
        PhraseEntry(text: "来源", code: "goid", type: 2, hint: "来(GO) + 源(ID)"),
        PhraseEntry(text: "交流", code: "uqiy", type: 2, hint: "交(UQ) + 流(IY)"),
        PhraseEntry(text: "详细", code: "yuxl", type: 2, hint: "详(YU) + 细(XL)"),
        PhraseEntry(text: "选择", code: "tfrc", type: 2, hint: "选(TF) + 择(RC)"),
        PhraseEntry(text: "大家", code: "ddpe", type: 2, hint: "大(DD) + 家(PE)"),
        PhraseEntry(text: "版主", code: "thyg", type: 2, hint: "版(TH) + 主(YG)"),
        PhraseEntry(text: "通过", code: "cefp", type: 2, hint: "通(CE) + 过(FP)"),
        PhraseEntry(text: "名称", code: "qktq", type: 2, hint: "名(QK) + 称(TQ)"),
        PhraseEntry(text: "出来", code: "bmgo", type: 2, hint: "出(BM) + 来(GO)"),
        PhraseEntry(text: "当前", code: "ivue", type: 2, hint: "当(IV) + 前(UE)"),
        PhraseEntry(text: "地方", code: "fbyy", type: 2, hint: "地(FB) + 方(YY)"),
        PhraseEntry(text: "介绍", code: "wjxv", type: 2, hint: "介(WJ) + 绍(XV)"),
        PhraseEntry(text: "资讯", code: "uqyn", type: 2, hint: "资(UQ) + 讯(YN)"),
        PhraseEntry(text: "资料", code: "uqou", type: 2, hint: "资(UQ) + 料(OU)"),
        PhraseEntry(text: "这样", code: "ypsu", type: 2, hint: "这(YP) + 样(SU)"),
        PhraseEntry(text: "日期", code: "jjad", type: 2, hint: "日(JJ) + 期(AD)"),
        PhraseEntry(text: "链接", code: "qlru", type: 2, hint: "链(QL) + 接(RU)"),
        PhraseEntry(text: "国内", code: "lgmw", type: 2, hint: "国(LG) + 内(MW)"),
        PhraseEntry(text: "美容", code: "ugpw", type: 2, hint: "美(UG) + 容(PW)"),
        PhraseEntry(text: "阅读", code: "uuyf", type: 2, hint: "阅(UU) + 读(YF)"),
        PhraseEntry(text: "开始", code: "gavc", type: 2, hint: "开(GA) + 始(VC)"),
        PhraseEntry(text: "系统", code: "txxy", type: 2, hint: "系(TX) + 统(XY)"),
        PhraseEntry(text: "工具", code: "aahw", type: 2, hint: "工(AA) + 具(HW)"),
        PhraseEntry(text: "所以", code: "rnny", type: 2, hint: "所(RN) + 以(NY)"),
        PhraseEntry(text: "广告", code: "yytf", type: 2, hint: "广(YY) + 告(TF)"),
        PhraseEntry(text: "返回", code: "rclk", type: 2, hint: "返(RC) + 回(LK)"),
        PhraseEntry(text: "用品", code: "etkk", type: 2, hint: "用(ET) + 品(KK)"),
        PhraseEntry(text: "就是", code: "yijg", type: 2, hint: "就(YI) + 是(JG)"),
        PhraseEntry(text: "设计", code: "ymyf", type: 2, hint: "设(YM) + 计(YF)"),
        PhraseEntry(text: "因为", code: "ldyl", type: 2, hint: "因(LD) + 为(YL)"),
        PhraseEntry(text: "编辑", code: "xylk", type: 2, hint: "编(XY) + 辑(LK)"),
        PhraseEntry(text: "一下", code: "gggh", type: 2, hint: "一(GG) + 下(GH)"),
        PhraseEntry(text: "经济", code: "xciy", type: 2, hint: "经(XC) + 济(IY)"),
        PhraseEntry(text: "显示", code: "jofi", type: 2, hint: "显(JO) + 示(FI)"),
        PhraseEntry(text: "地域", code: "fbfa", type: 2, hint: "地(FB) + 域(FA)"),
        PhraseEntry(text: "频道", code: "hiut", type: 2, hint: "频(HI) + 道(UT)"),
        PhraseEntry(text: "关闭", code: "uduf", type: 2, hint: "关(UD) + 闭(UF)"),
        PhraseEntry(text: "一定", code: "ggpg", type: 2, hint: "一(GG) + 定(PG)"),
        PhraseEntry(text: "地图", code: "fblt", type: 2, hint: "地(FB) + 图(LT)"),
        PhraseEntry(text: "社区", code: "pyaq", type: 2, hint: "社(PY) + 区(AQ)"),
        PhraseEntry(text: "投票", code: "rmsf", type: 2, hint: "投(RM) + 票(SF)"),
        PhraseEntry(text: "参加", code: "cdlk", type: 2, hint: "参(CD) + 加(LK)"),
        PhraseEntry(text: "建议", code: "vfyy", type: 2, hint: "建(VF) + 议(YY)"),
        PhraseEntry(text: "城市", code: "fdym", type: 2, hint: "城(FD) + 市(YM)"),
        PhraseEntry(text: "友情", code: "dcng", type: 2, hint: "友(DC) + 情(NG)"),
        PhraseEntry(text: "更多", code: "gjqq", type: 2, hint: "更(GJ) + 多(QQ)"),
        PhraseEntry(text: "分析", code: "wvsr", type: 2, hint: "分(WV) + 析(SR)"),
        PhraseEntry(text: "旅行", code: "yttf", type: 2, hint: "旅(YT) + 行(TF)"),
        PhraseEntry(text: "也是", code: "bnjg", type: 2, hint: "也(BN) + 是(JG)"),
        PhraseEntry(text: "一次", code: "gguq", type: 2, hint: "一(GG) + 次(UQ)"),
        PhraseEntry(text: "消息", code: "iith", type: 2, hint: "消(II) + 息(TH)"),
        PhraseEntry(text: "回复", code: "lktj", type: 2, hint: "回(LK) + 复(TJ)"),
        PhraseEntry(text: "方面", code: "yydm", type: 2, hint: "方(YY) + 面(DM)"),
        PhraseEntry(text: "作品", code: "wtkk", type: 2, hint: "作(WT) + 品(KK)"),
        PhraseEntry(text: "指定", code: "rxpg", type: 2, hint: "指(RX) + 定(PG)"),
        PhraseEntry(text: "香港", code: "tjia", type: 2, hint: "香(TJ) + 港(IA)"),
        PhraseEntry(text: "你的", code: "wqrq", type: 2, hint: "你(WQ) + 的(RQ)"),
        PhraseEntry(text: "文化", code: "yywx", type: 2, hint: "文(YY) + 化(WX)"),
        PhraseEntry(text: "网上", code: "mqhh", type: 2, hint: "网(MQ) + 上(HH)"),
        PhraseEntry(text: "以及", code: "nyey", type: 2, hint: "以(NY) + 及(EY)"),
        PhraseEntry(text: "有戏", code: "deca", type: 2, hint: "有(DE) + 戏(CA)"),
        PhraseEntry(text: "而言", code: "dmyy", type: 2, hint: "而(DM) + 言(YY)"),
        PhraseEntry(text: "但是", code: "wjjg", type: 2, hint: "但(WJ) + 是(JG)"),
        PhraseEntry(text: "番号", code: "tokg", type: 2, hint: "番(TO) + 号(KG)"),
        PhraseEntry(text: "而成", code: "dmdn", type: 2, hint: "而(DM) + 成(DN)"),
        PhraseEntry(text: "还是", code: "gijg", type: 2, hint: "还(GI) + 是(JG)"),
        PhraseEntry(text: "普通", code: "uoce", type: 2, hint: "普(UO) + 通(CE)"),
        PhraseEntry(text: "上海", code: "hhit", type: 2, hint: "上(HH) + 海(IT)"),
        PhraseEntry(text: "本文", code: "sgyy", type: 2, hint: "本(SG) + 文(YY)"),
        PhraseEntry(text: "接口", code: "rukk", type: 2, hint: "接(RU) + 口(KK)"),
        PhraseEntry(text: "大学", code: "ddip", type: 2, hint: "大(DD) + 学(IP)"),
        PhraseEntry(text: "简介", code: "tuwj", type: 2, hint: "简(TU) + 介(WJ)"),
        PhraseEntry(text: "解决", code: "qeun", type: 2, hint: "解(QE) + 决(UN)"),
        PhraseEntry(text: "今天", code: "wygd", type: 2, hint: "今(WY) + 天(GD)"),
        PhraseEntry(text: "责任", code: "gmwt", type: 2, hint: "责(GM) + 任(WT)"),
        PhraseEntry(text: "完全", code: "pfwg", type: 2, hint: "完(PF) + 全(WG)"),
        PhraseEntry(text: "情况", code: "nguk", type: 2, hint: "情(NG) + 况(UK)"),
        PhraseEntry(text: "标题", code: "sfjg", type: 2, hint: "标(SF) + 题(JG)"),
        PhraseEntry(text: "交易", code: "uqjq", type: 2, hint: "交(UQ) + 易(JQ)"),
        PhraseEntry(text: "共有", code: "awde", type: 2, hint: "共(AW) + 有(DE)"),
        PhraseEntry(text: "同时", code: "mgjf", type: 2, hint: "同(MG) + 时(JF)"),
        PhraseEntry(text: "自然", code: "thqd", type: 2, hint: "自(TH) + 然(QD)"),
        PhraseEntry(text: "音乐", code: "ujqi", type: 2, hint: "音(UJ) + 乐(QI)"),
        PhraseEntry(text: "今年", code: "wyrh", type: 2, hint: "今(WY) + 年(RH)"),
        PhraseEntry(text: "文字", code: "yypb", type: 2, hint: "文(YY) + 字(PB)"),
        PhraseEntry(text: "出版", code: "bmth", type: 2, hint: "出(BM) + 版(TH)"),
        PhraseEntry(text: "打印", code: "rsqg", type: 2, hint: "打(RS) + 印(QG)"),
        PhraseEntry(text: "添加", code: "iglk", type: 2, hint: "添(IG) + 加(LK)"),
        PhraseEntry(text: "发现", code: "ntgm", type: 2, hint: "发(NT) + 现(GM)"),
        PhraseEntry(text: "目的", code: "hhrq", type: 2, hint: "目(HH) + 的(RQ)"),
        PhraseEntry(text: "包括", code: "qnrt", type: 2, hint: "包(QN) + 括(RT)"),
        PhraseEntry(text: "价格", code: "wwst", type: 2, hint: "价(WW) + 格(ST)"),
        PhraseEntry(text: "一切", code: "ggav", type: 2, hint: "一(GG) + 切(AV)"),
        PhraseEntry(text: "金融", code: "qqgk", type: 2, hint: "金(QQ) + 融(GK)"),
        PhraseEntry(text: "很多", code: "tvqq", type: 2, hint: "很(TV) + 多(QQ)"),
        PhraseEntry(text: "而是", code: "dmjg", type: 2, hint: "而(DM) + 是(JG)"),
        PhraseEntry(text: "成功", code: "dnal", type: 2, hint: "成(DN) + 功(AL)"),
        PhraseEntry(text: "一些", code: "gghx", type: 2, hint: "一(GG) + 些(HX)"),
        PhraseEntry(text: "怎么", code: "thtc", type: 2, hint: "怎(TH) + 么(TC)"),
        PhraseEntry(text: "最高", code: "jbym", type: 2, hint: "最(JB) + 高(YM)"),
        PhraseEntry(text: "浏览", code: "iyjt", type: 2, hint: "浏(IY) + 览(JT)"),
        PhraseEntry(text: "建设", code: "vfym", type: 2, hint: "建(VF) + 设(YM)"),
        PhraseEntry(text: "出现", code: "bmgm", type: 2, hint: "出(BM) + 现(GM)"),
        PhraseEntry(text: "黑色", code: "lfqc", type: 2, hint: "黑(LF) + 色(QC)"),
        PhraseEntry(text: "记录", code: "ynvi", type: 2, hint: "记(YN) + 录(VI)"),
        PhraseEntry(text: "控制", code: "rprm", type: 2, hint: "控(RP) + 制(RM)"),
        PhraseEntry(text: "交通", code: "uqce", type: 2, hint: "交(UQ) + 通(CE)"),
        PhraseEntry(text: "外部", code: "qhuk", type: 2, hint: "外(QH) + 部(UK)"),
        PhraseEntry(text: "科技", code: "turf", type: 2, hint: "科(TU) + 技(RF)"),
        PhraseEntry(text: "中央", code: "khmd", type: 2, hint: "中(KH) + 央(MD)"),
        PhraseEntry(text: "只有", code: "kwde", type: 2, hint: "只(KW) + 有(DE)"),
        PhraseEntry(text: "这里", code: "ypjf", type: 2, hint: "这(YP) + 里(JF)"),
        PhraseEntry(text: "转载", code: "lffa", type: 2, hint: "转(LF) + 载(FA)"),
        PhraseEntry(text: "娱乐", code: "vkqi", type: 2, hint: "娱(VK) + 乐(QI)"),
        PhraseEntry(text: "品牌", code: "kkth", type: 2, hint: "品(KK) + 牌(TH)"),
        PhraseEntry(text: "国家", code: "lgpe", type: 2, hint: "国(LG) + 家(PE)"),
        PhraseEntry(text: "生产", code: "tgut", type: 2, hint: "生(TG) + 产(UT)"),
        PhraseEntry(text: "说明", code: "yuje", type: 2, hint: "说(YU) + 明(JE)"),
        PhraseEntry(text: "汽车", code: "irlg", type: 2, hint: "汽(IR) + 车(LG)"),
        PhraseEntry(text: "标准", code: "sfuw", type: 2, hint: "标(SF) + 准(UW)"),
        PhraseEntry(text: "分享", code: "wvyb", type: 2, hint: "分(WV) + 享(YB)"),
        PhraseEntry(text: "人员", code: "wwkm", type: 2, hint: "人(WW) + 员(KM)"),
        PhraseEntry(text: "统计", code: "xyyf", type: 2, hint: "统(XY) + 计(YF)"),
        PhraseEntry(text: "声明", code: "fnje", type: 2, hint: "声(FN) + 明(JE)"),
        PhraseEntry(text: "综合", code: "xpwg", type: 2, hint: "综(XP) + 合(WG)"),
        PhraseEntry(text: "能力", code: "celt", type: 2, hint: "能(CE) + 力(LT)"),
        PhraseEntry(text: "完成", code: "pfdn", type: 2, hint: "完(PF) + 成(DN)"),
        PhraseEntry(text: "开发", code: "gant", type: 2, hint: "开(GA) + 发(NT)"),
        PhraseEntry(text: "功能", code: "alce", type: 2, hint: "功(AL) + 能(CE)"),
        PhraseEntry(text: "好的", code: "vbrq", type: 2, hint: "好(VB) + 的(RQ)"),
        PhraseEntry(text: "业务", code: "ogtl", type: 2, hint: "业(OG) + 务(TL)"),
        PhraseEntry(text: "这些", code: "yphx", type: 2, hint: "这(YP) + 些(HX)"),
        PhraseEntry(text: "地区", code: "fbaq", type: 2, hint: "地(FB) + 区(AQ)"),
        PhraseEntry(text: "积分", code: "tkwv", type: 2, hint: "积(TK) + 分(WV)"),
        PhraseEntry(text: "政府", code: "ghyw", type: 2, hint: "政(GH) + 府(YW)"),
        PhraseEntry(text: "软件", code: "lqwr", type: 2, hint: "软(LQ) + 件(WR)"),
        PhraseEntry(text: "操作", code: "rkwt", type: 2, hint: "操(RK) + 作(WT)"),
        PhraseEntry(text: "热门", code: "rvuy", type: 2, hint: "热(RV) + 门(UY)"),
        PhraseEntry(text: "取得", code: "bctj", type: 2, hint: "取(BC) + 得(TJ)"),
        PhraseEntry(text: "进入", code: "fjty", type: 2, hint: "进(FJ) + 入(TY)"),
        PhraseEntry(text: "时候", code: "jfwh", type: 2, hint: "时(JF) + 候(WH)"),
        PhraseEntry(text: "很大", code: "tvdd", type: 2, hint: "很(TV) + 大(DD)"),
        PhraseEntry(text: "订阅", code: "ysuu", type: 2, hint: "订(YS) + 阅(UU)"),
        PhraseEntry(text: "关键", code: "udqv", type: 2, hint: "关(UD) + 键(QV)"),
        PhraseEntry(text: "快速", code: "nngk", type: 2, hint: "快(NN) + 速(GK)"),
        PhraseEntry(text: "住所", code: "wyrn", type: 2, hint: "住(WY) + 所(RN)"),
        PhraseEntry(text: "或者", code: "akft", type: 2, hint: "或(AK) + 者(FT)"),
        PhraseEntry(text: "限定", code: "bvpg", type: 2, hint: "限(BV) + 定(PG)"),
        PhraseEntry(text: "存在", code: "dhdh", type: 2, hint: "存(DH) + 在(DH)"),
        PhraseEntry(text: "成为", code: "dnyl", type: 2, hint: "成(DN) + 为(YL)"),
        PhraseEntry(text: "一直", code: "ggfh", type: 2, hint: "一(GG) + 直(FH)"),
        PhraseEntry(text: "不同", code: "gimg", type: 2, hint: "不(GI) + 同(MG)"),
        PhraseEntry(text: "学校", code: "ipsu", type: 2, hint: "学(IP) + 校(SU)"),
        PhraseEntry(text: "游戏", code: "iyca", type: 2, hint: "游(IY) + 戏(CA)"),
        PhraseEntry(text: "意见", code: "ujmq", type: 2, hint: "意(UJ) + 见(MQ)"),
        PhraseEntry(text: "他们", code: "wbwu", type: 2, hint: "他(WB) + 们(WU)"),
        PhraseEntry(text: "原因", code: "drld", type: 2, hint: "原(DR) + 因(LD)"),
        PhraseEntry(text: "看到", code: "rhgc", type: 2, hint: "看(RH) + 到(GC)"),
        PhraseEntry(text: "程度", code: "tkya", type: 2, hint: "程(TK) + 度(YA)"),
        PhraseEntry(text: "公告", code: "wctf", type: 2, hint: "公(WC) + 告(TF)"),
        PhraseEntry(text: "百度", code: "djya", type: 2, hint: "百(DJ) + 度(YA)"),
        PhraseEntry(text: "知识", code: "tdyk", type: 2, hint: "知(TD) + 识(YK)"),
        PhraseEntry(text: "新品", code: "uskk", type: 2, hint: "新(US) + 品(KK)"),
        PhraseEntry(text: "小时", code: "ihjf", type: 2, hint: "小(IH) + 时(JF)"),
        PhraseEntry(text: "展示", code: "nafi", type: 2, hint: "展(NA) + 示(FI)"),
        PhraseEntry(text: "为了", code: "ylbn", type: 2, hint: "为(YL) + 了(BN)"),
        PhraseEntry(text: "其中", code: "adkh", type: 2, hint: "其(AD) + 中(KH)"),
        PhraseEntry(text: "学生", code: "iptg", type: 2, hint: "学(IP) + 生(TG)"),
        PhraseEntry(text: "提高", code: "rjym", type: 2, hint: "提(RJ) + 高(YM)"),
        PhraseEntry(text: "引用", code: "xhet", type: 2, hint: "引(XH) + 用(ET)"),
        PhraseEntry(text: "维修", code: "xwwh", type: 2, hint: "维(XW) + 修(WH)"),
        PhraseEntry(text: "经营", code: "xcap", type: 2, hint: "经(XC) + 营(AP)"),
        PhraseEntry(text: "设备", code: "ymtl", type: 2, hint: "设(YM) + 备(TL)"),
        PhraseEntry(text: "有关", code: "deud", type: 2, hint: "有(DE) + 关(UD)"),
        PhraseEntry(text: "只是", code: "kwjg", type: 2, hint: "只(KW) + 是(JG)"),
        PhraseEntry(text: "平均", code: "gufq", type: 2, hint: "平(GU) + 均(FQ)"),
        PhraseEntry(text: "交友", code: "uqdc", type: 2, hint: "交(UQ) + 友(DC)"),
        PhraseEntry(text: "离线", code: "ybxg", type: 2, hint: "离(YB) + 线(XG)"),
        PhraseEntry(text: "正在", code: "ghdh", type: 2, hint: "正(GH) + 在(DH)"),
        PhraseEntry(text: "网友", code: "mqdc", type: 2, hint: "网(MQ) + 友(DC)"),
        PhraseEntry(text: "导航", code: "nfte", type: 2, hint: "导(NF) + 航(TE)"),
        PhraseEntry(text: "文件", code: "yywr", type: 2, hint: "文(YY) + 件(WR)"),
        PhraseEntry(text: "分钟", code: "wvqk", type: 2, hint: "分(WV) + 钟(QK)"),
        PhraseEntry(text: "其它", code: "adpx", type: 2, hint: "其(AD) + 它(PX)"),
        PhraseEntry(text: "了解", code: "bnqe", type: 2, hint: "了(BN) + 解(QE)"),
        PhraseEntry(text: "家庭", code: "peyt", type: 2, hint: "家(PE) + 庭(YT)"),
        PhraseEntry(text: "大阪", code: "ddbr", type: 2, hint: "大(DD) + 阪(BR)"),
        PhraseEntry(text: "密码", code: "pndc", type: 2, hint: "密(PN) + 码(DC)"),
        PhraseEntry(text: "动态", code: "fcdy", type: 2, hint: "动(FC) + 态(DY)"),
        PhraseEntry(text: "学习", code: "ipnu", type: 2, hint: "学(IP) + 习(NU)"),
        PhraseEntry(text: "比较", code: "xxlu", type: 2, hint: "比(XX) + 较(LU)"),
        PhraseEntry(text: "应该", code: "yiyy", type: 2, hint: "应(YI) + 该(YY)"),
        PhraseEntry(text: "便利", code: "wgtj", type: 2, hint: "便(WG) + 利(TJ)"),
        PhraseEntry(text: "海外", code: "itqh", type: 2, hint: "海(IT) + 外(QH)"),
        PhraseEntry(text: "邮箱", code: "mbts", type: 2, hint: "邮(MB) + 箱(TS)"),
        PhraseEntry(text: "喜欢", code: "fkcq", type: 2, hint: "喜(FK) + 欢(CQ)"),
        PhraseEntry(text: "利益", code: "tjuw", type: 2, hint: "利(TJ) + 益(UW)"),
        PhraseEntry(text: "电影", code: "jnjy", type: 2, hint: "电(JN) + 影(JY)"),
        PhraseEntry(text: "由于", code: "mhgf", type: 2, hint: "由(MH) + 于(GF)"),
        PhraseEntry(text: "以前", code: "nyue", type: 2, hint: "以(NY) + 前(UE)"),
        PhraseEntry(text: "根据", code: "svrn", type: 2, hint: "根(SV) + 据(RN)"),
        PhraseEntry(text: "政策", code: "ghtg", type: 2, hint: "政(GH) + 策(TG)"),
        PhraseEntry(text: "关注", code: "udiy", type: 2, hint: "关(UD) + 注(IY)"),
        PhraseEntry(text: "通常", code: "ceip", type: 2, hint: "通(CE) + 常(IP)"),
        PhraseEntry(text: "一起", code: "ggfh", type: 2, hint: "一(GG) + 起(FH)"),
        PhraseEntry(text: "注目", code: "iyhh", type: 2, hint: "注(IY) + 目(HH)"),
        PhraseEntry(text: "客服", code: "pteb", type: 2, hint: "客(PT) + 服(EB)"),
        PhraseEntry(text: "用户名", code: "eyqk", type: 3, hint: "用(E) + 户(Y) + 名(QK)"),
        PhraseEntry(text: "大多数", code: "dqov", type: 3, hint: "大(D) + 多(Q) + 数(OV)"),
        PhraseEntry(text: "共和国", code: "atlg", type: 3, hint: "共(A) + 和(T) + 国(LG)"),
        PhraseEntry(text: "关键字", code: "uqpb", type: 3, hint: "关(U) + 键(Q) + 字(PB)"),
        PhraseEntry(text: "为什么", code: "ywtc", type: 3, hint: "为(Y) + 什(W) + 么(TC)"),
        PhraseEntry(text: "出版社", code: "btpy", type: 3, hint: "出(B) + 版(T) + 社(PY)"),
        PhraseEntry(text: "通行证", code: "ctyg", type: 3, hint: "通(C) + 行(T) + 证(YG)"),
        PhraseEntry(text: "所在地", code: "rdfb", type: 3, hint: "所(R) + 在(D) + 地(FB)"),
        PhraseEntry(text: "留言板", code: "qysr", type: 3, hint: "留(Q) + 言(Y) + 板(SR)"),
        PhraseEntry(text: "排行榜", code: "rtsu", type: 3, hint: "排(R) + 行(T) + 榜(SU)"),
        PhraseEntry(text: "进一步", code: "fghi", type: 3, hint: "进(F) + 一(G) + 步(HI)"),
        PhraseEntry(text: "大学生", code: "ditg", type: 3, hint: "大(D) + 学(I) + 生(TG)"),
        PhraseEntry(text: "可能性", code: "scnt", type: 3, hint: "可(S) + 能(C) + 性(NT)"),
        PhraseEntry(text: "是不是", code: "jgjg", type: 3, hint: "是(J) + 不(G) + 是(JG)"),
        PhraseEntry(text: "北海道", code: "uiut", type: 3, hint: "北(U) + 海(I) + 道(UT)"),
        PhraseEntry(text: "办公室", code: "lwpg", type: 3, hint: "办(L) + 公(W) + 室(PG)"),
        PhraseEntry(text: "互联网", code: "gbmq", type: 3, hint: "互(G) + 联(B) + 网(MQ)"),
        PhraseEntry(text: "计算机", code: "ytsm", type: 3, hint: "计(Y) + 算(T) + 机(SM)"),
        PhraseEntry(text: "笔记本", code: "tysg", type: 3, hint: "笔(T) + 记(Y) + 本(SG)"),
        PhraseEntry(text: "收藏夹", code: "nagu", type: 3, hint: "收(N) + 藏(A) + 夹(GU)"),
        PhraseEntry(text: "俱乐部", code: "wquk", type: 3, hint: "俱(W) + 乐(Q) + 部(UK)"),
        PhraseEntry(text: "北京市", code: "uyym", type: 3, hint: "北(U) + 京(Y) + 市(YM)"),
        PhraseEntry(text: "名古屋", code: "qdng", type: 3, hint: "名(Q) + 古(D) + 屋(NG)"),
        PhraseEntry(text: "服务器", code: "etkk", type: 3, hint: "服(E) + 务(T) + 器(KK)"),
        PhraseEntry(text: "一般人", code: "gtww", type: 3, hint: "一(G) + 般(T) + 人(WW)"),
        PhraseEntry(text: "黑龙江", code: "ldia", type: 3, hint: "黑(L) + 龙(D) + 江(IA)"),
        PhraseEntry(text: "工作室", code: "awpg", type: 3, hint: "工(A) + 作(W) + 室(PG)"),
        PhraseEntry(text: "数据库", code: "oryl", type: 3, hint: "数(O) + 据(R) + 库(YL)"),
        PhraseEntry(text: "手续费", code: "rxxj", type: 3, hint: "手(R) + 续(X) + 费(XJ)"),
        PhraseEntry(text: "墨西哥", code: "lssk", type: 3, hint: "墨(L) + 西(S) + 哥(SK)"),
        PhraseEntry(text: "电视剧", code: "jpnd", type: 3, hint: "电(J) + 视(P) + 剧(ND)"),
        PhraseEntry(text: "越来越", code: "fgfh", type: 3, hint: "越(F) + 来(G) + 越(FH)"),
        PhraseEntry(text: "委员会", code: "tkwf", type: 3, hint: "委(T) + 员(K) + 会(WF)"),
        PhraseEntry(text: "负责人", code: "qgww", type: 3, hint: "负(Q) + 责(G) + 人(WW)"),
        PhraseEntry(text: "星期四", code: "jalh", type: 3, hint: "星(J) + 期(A) + 四(LH)"),
        PhraseEntry(text: "土耳其", code: "fbad", type: 3, hint: "土(F) + 耳(B) + 其(AD)"),
        PhraseEntry(text: "隐私权", code: "btsc", type: 3, hint: "隐(B) + 私(T) + 权(SC)"),
        PhraseEntry(text: "哈尔滨", code: "kqip", type: 3, hint: "哈(K) + 尔(Q) + 滨(IP)"),
        PhraseEntry(text: "小学生", code: "iitg", type: 3, hint: "小(I) + 学(I) + 生(TG)"),
        PhraseEntry(text: "显示器", code: "jfkk", type: 3, hint: "显(J) + 示(F) + 器(KK)"),
        PhraseEntry(text: "管理员", code: "tgkm", type: 3, hint: "管(T) + 理(G) + 员(KM)"),
        PhraseEntry(text: "日用品", code: "jekk", type: 3, hint: "日(J) + 用(E) + 品(KK)"),
        PhraseEntry(text: "平方米", code: "gyoy", type: 3, hint: "平(G) + 方(Y) + 米(OY)"),
        PhraseEntry(text: "人民币", code: "wntm", type: 3, hint: "人(W) + 民(N) + 币(TM)"),
        PhraseEntry(text: "研究所", code: "dprn", type: 3, hint: "研(D) + 究(P) + 所(RN)"),
        PhraseEntry(text: "刘少奇", code: "yids", type: 3, hint: "刘(Y) + 少(I) + 奇(DS)"),
        PhraseEntry(text: "国内外", code: "lmqh", type: 3, hint: "国(L) + 内(M) + 外(QH)"),
        PhraseEntry(text: "不可能", code: "gsce", type: 3, hint: "不(G) + 可(S) + 能(CE)"),
        PhraseEntry(text: "房地产", code: "yfut", type: 3, hint: "房(Y) + 地(F) + 产(UT)"),
        PhraseEntry(text: "太平洋", code: "dgiu", type: 3, hint: "太(D) + 平(G) + 洋(IU)"),
        PhraseEntry(text: "版权所有", code: "bqsy", type: 4, hint: "版(T) + 权(S) + 所(R) + 有(D)"),
        PhraseEntry(text: "株式会社", code: "sawp", type: 4, hint: "株(S) + 式(A) + 会(W) + 社(P)"),
        PhraseEntry(text: "有限公司", code: "dbwn", type: 4, hint: "有(D) + 限(B) + 公(W) + 司(N)"),
        PhraseEntry(text: "阿里巴巴", code: "bjcc", type: 4, hint: "阿(B) + 里(J) + 巴(C) + 巴(C)"),
        PhraseEntry(text: "操作系统", code: "rwtx", type: 4, hint: "操(R) + 作(W) + 系(T) + 统(X)"),
        PhraseEntry(text: "解决方案", code: "quyp", type: 4, hint: "解(Q) + 决(U) + 方(Y) + 案(P)"),
        PhraseEntry(text: "不得而知", code: "gtdt", type: 4, hint: "不(G) + 得(T) + 而(D) + 知(T)"),
        PhraseEntry(text: "中国人民", code: "klwn", type: 4, hint: "中(K) + 国(L) + 人(W) + 民(N)"),
        PhraseEntry(text: "谈天说地", code: "ygyf", type: 4, hint: "谈(Y) + 天(G) + 说(Y) + 地(F)"),
        PhraseEntry(text: "澳大利亚", code: "idtg", type: 4, hint: "澳(I) + 大(D) + 利(T) + 亚(G)"),
        PhraseEntry(text: "不好意思", code: "gvul", type: 4, hint: "不(G) + 好(V) + 意(U) + 思(L)"),
        PhraseEntry(text: "改革开放", code: "nagy", type: 4, hint: "改(N) + 革(A) + 开(G) + 放(Y)"),
        PhraseEntry(text: "招商引资", code: "ruxu", type: 4, hint: "招(R) + 商(U) + 引(X) + 资(U)"),
        PhraseEntry(text: "除此之外", code: "bhpq", type: 4, hint: "除(B) + 此(H) + 之(P) + 外(Q)"),
        PhraseEntry(text: "也就是说", code: "byjy", type: 4, hint: "也(B) + 就(Y) + 是(J) + 说(Y)"),
        PhraseEntry(text: "爸爸妈妈", code: "wwvv", type: 4, hint: "爸(W) + 爸(W) + 妈(V) + 妈(V)"),
        PhraseEntry(text: "社会主义", code: "pwyy", type: 4, hint: "社(P) + 会(W) + 主(Y) + 义(Y)"),
        PhraseEntry(text: "高速公路", code: "ygwk", type: 4, hint: "高(Y) + 速(G) + 公(W) + 路(K)"),
        PhraseEntry(text: "乌鲁木齐", code: "qqsy", type: 4, hint: "乌(Q) + 鲁(Q) + 木(S) + 齐(Y)"),
        PhraseEntry(text: "津津有味", code: "iidk", type: 4, hint: "津(I) + 津(I) + 有(D) + 味(K)"),
        PhraseEntry(text: "摩托罗拉", code: "yrlr", type: 4, hint: "摩(Y) + 托(R) + 罗(L) + 拉(R)"),
        PhraseEntry(text: "后顾之忧", code: "rdpn", type: 4, hint: "后(R) + 顾(D) + 之(P) + 忧(N)"),
        PhraseEntry(text: "送货上门", code: "uwhu", type: 4, hint: "送(U) + 货(W) + 上(H) + 门(U)"),
        PhraseEntry(text: "时时刻刻", code: "jjyy", type: 4, hint: "时(J) + 时(J) + 刻(Y) + 刻(Y)"),
        PhraseEntry(text: "黑龙江省", code: "ldii", type: 4, hint: "黑(L) + 龙(D) + 江(I) + 省(I)"),
        PhraseEntry(text: "马来西亚", code: "cgsg", type: 4, hint: "马(C) + 来(G) + 西(S) + 亚(G)"),
        PhraseEntry(text: "图文并茂", code: "lyua", type: 4, hint: "图(L) + 文(Y) + 并(U) + 茂(A)"),
        PhraseEntry(text: "吃喝玩乐", code: "kkgq", type: 4, hint: "吃(K) + 喝(K) + 玩(G) + 乐(Q)"),
        PhraseEntry(text: "一点也不", code: "ghbg", type: 4, hint: "一(G) + 点(H) + 也(B) + 不(G)"),
        PhraseEntry(text: "以人为本", code: "nwys", type: 4, hint: "以(N) + 人(W) + 为(Y) + 本(S)"),
        PhraseEntry(text: "卡巴斯基", code: "hcaa", type: 4, hint: "卡(H) + 巴(C) + 斯(A) + 基(A)"),
        PhraseEntry(text: "呼和浩特", code: "ktit", type: 4, hint: "呼(K) + 和(T) + 浩(I) + 特(T)"),
        PhraseEntry(text: "齐齐哈尔", code: "yykq", type: 4, hint: "齐(Y) + 齐(Y) + 哈(K) + 尔(Q)"),
        PhraseEntry(text: "必由之路", code: "nmpk", type: 4, hint: "必(N) + 由(M) + 之(P) + 路(K)"),
        PhraseEntry(text: "巴勒斯坦", code: "caaf", type: 4, hint: "巴(C) + 勒(A) + 斯(A) + 坦(F)"),
        PhraseEntry(text: "巴基斯坦", code: "caaf", type: 4, hint: "巴(C) + 基(A) + 斯(A) + 坦(F)"),
        PhraseEntry(text: "一模一样", code: "gsgs", type: 4, hint: "一(G) + 模(S) + 一(G) + 样(S)"),
        PhraseEntry(text: "不知不觉", code: "gtgi", type: 4, hint: "不(G) + 知(T) + 不(G) + 觉(I)"),
        PhraseEntry(text: "海阔天空", code: "iugp", type: 4, hint: "海(I) + 阔(U) + 天(G) + 空(P)"),
        PhraseEntry(text: "遵纪守法", code: "uxpi", type: 4, hint: "遵(U) + 纪(X) + 守(P) + 法(I)"),
        PhraseEntry(text: "雁过留声", code: "dfqf", type: 4, hint: "雁(D) + 过(F) + 留(Q) + 声(F)"),
        PhraseEntry(text: "奥林匹克", code: "tsad", type: 4, hint: "奥(T) + 林(S) + 匹(A) + 克(D)"),
        PhraseEntry(text: "前所未有", code: "urfd", type: 4, hint: "前(U) + 所(R) + 未(F) + 有(D)"),
        PhraseEntry(text: "真知灼见", code: "ftom", type: 4, hint: "真(F) + 知(T) + 灼(O) + 见(M)"),
        PhraseEntry(text: "七嘴八舌", code: "akwt", type: 4, hint: "七(A) + 嘴(K) + 八(W) + 舌(T)"),
        PhraseEntry(text: "各种各样", code: "ttts", type: 4, hint: "各(T) + 种(T) + 各(T) + 样(S)"),
        PhraseEntry(text: "莫名其妙", code: "aqav", type: 4, hint: "莫(A) + 名(Q) + 其(A) + 妙(V)"),
        PhraseEntry(text: "未成年人", code: "fdrw", type: 4, hint: "未(F) + 成(D) + 年(R) + 人(W)"),
        PhraseEntry(text: "绝大多数", code: "xdqo", type: 4, hint: "绝(X) + 大(D) + 多(Q) + 数(O)"),
        PhraseEntry(text: "招贤纳士", code: "rjxf", type: 4, hint: "招(R) + 贤(J) + 纳(X) + 士(F)"),
        PhraseEntry(text: "计划生育", code: "yaty", type: 4, hint: "计(Y) + 划(A) + 生(T) + 育(Y)"),
        PhraseEntry(text: "一见钟情", code: "gmqn", type: 4, hint: "一(G) + 见(M) + 钟(Q) + 情(N)"),
        PhraseEntry(text: "绝大部分", code: "xduw", type: 4, hint: "绝(X) + 大(D) + 部(U) + 分(W)"),
        PhraseEntry(text: "兄弟姐妹", code: "kuvv", type: 4, hint: "兄(K) + 弟(U) + 姐(V) + 妹(V)"),
        PhraseEntry(text: "无处不在", code: "ftgd", type: 4, hint: "无(F) + 处(T) + 不(G) + 在(D)"),
        PhraseEntry(text: "无论如何", code: "fyvw", type: 4, hint: "无(F) + 论(Y) + 如(V) + 何(W)"),
        PhraseEntry(text: "色即是空", code: "qvjp", type: 4, hint: "色(Q) + 即(V) + 是(J) + 空(P)"),
        PhraseEntry(text: "不可思议", code: "gsly", type: 4, hint: "不(G) + 可(S) + 思(L) + 议(Y)"),
        PhraseEntry(text: "花开花落", code: "agaa", type: 4, hint: "花(A) + 开(G) + 花(A) + 落(A)"),
        PhraseEntry(text: "阿尔卡特", code: "bqht", type: 4, hint: "阿(B) + 尔(Q) + 卡(H) + 特(T)"),
        PhraseEntry(text: "奥林巴斯", code: "tsca", type: 4, hint: "奥(T) + 林(S) + 巴(C) + 斯(A)"),
        PhraseEntry(text: "顾名思义", code: "dqly", type: 4, hint: "顾(D) + 名(Q) + 思(L) + 义(Y)"),
        PhraseEntry(text: "自由自在", code: "tmtd", type: 4, hint: "自(T) + 由(M) + 自(T) + 在(D)"),
        PhraseEntry(text: "与众不同", code: "gwgm", type: 4, hint: "与(G) + 众(W) + 不(G) + 同(M)"),
        PhraseEntry(text: "点点滴滴", code: "hhii", type: 4, hint: "点(H) + 点(H) + 滴(I) + 滴(I)"),
        PhraseEntry(text: "人际关系", code: "wbut", type: 4, hint: "人(W) + 际(B) + 关(U) + 系(T)"),
        PhraseEntry(text: "一不小心", code: "ggin", type: 4, hint: "一(G) + 不(G) + 小(I) + 心(N)"),
        PhraseEntry(text: "百科全书", code: "dtwn", type: 4, hint: "百(D) + 科(T) + 全(W) + 书(N)"),
        PhraseEntry(text: "不由自主", code: "gmty", type: 4, hint: "不(G) + 由(M) + 自(T) + 主(Y)"),
        PhraseEntry(text: "实事求是", code: "pgfj", type: 4, hint: "实(P) + 事(G) + 求(F) + 是(J)"),
        PhraseEntry(text: "栩栩如生", code: "ssvt", type: 4, hint: "栩(S) + 栩(S) + 如(V) + 生(T)"),
        PhraseEntry(text: "可想而知", code: "ssdt", type: 4, hint: "可(S) + 想(S) + 而(D) + 知(T)"),
        PhraseEntry(text: "浦东新区", code: "iaua", type: 4, hint: "浦(I) + 东(A) + 新(U) + 区(A)"),
        PhraseEntry(text: "难得一见", code: "ctgm", type: 4, hint: "难(C) + 得(T) + 一(G) + 见(M)"),
        PhraseEntry(text: "一如既往", code: "gvvt", type: 4, hint: "一(G) + 如(V) + 既(V) + 往(T)"),
        PhraseEntry(text: "显而易见", code: "jdjm", type: 4, hint: "显(J) + 而(D) + 易(J) + 见(M)"),
        PhraseEntry(text: "大大小小", code: "ddii", type: 4, hint: "大(D) + 大(D) + 小(I) + 小(I)"),
        PhraseEntry(text: "五花八门", code: "gawu", type: 4, hint: "五(G) + 花(A) + 八(W) + 门(U)"),
        PhraseEntry(text: "不可或缺", code: "gsar", type: 4, hint: "不(G) + 可(S) + 或(A) + 缺(R)"),
        PhraseEntry(text: "必不可少", code: "ngsi", type: 4, hint: "必(N) + 不(G) + 可(S) + 少(I)"),
        PhraseEntry(text: "实实在在", code: "ppdd", type: 4, hint: "实(P) + 实(P) + 在(D) + 在(D)"),
        PhraseEntry(text: "抗美援朝", code: "rurf", type: 4, hint: "抗(R) + 美(U) + 援(R) + 朝(F)"),
        PhraseEntry(text: "共产党员", code: "auik", type: 4, hint: "共(A) + 产(U) + 党(I) + 员(K)"),
        PhraseEntry(text: "众所周知", code: "wrmt", type: 4, hint: "众(W) + 所(R) + 周(M) + 知(T)"),
        PhraseEntry(text: "靖国神社", code: "ulpp", type: 4, hint: "靖(U) + 国(L) + 神(P) + 社(P)"),
        PhraseEntry(text: "小心翼翼", code: "innn", type: 4, hint: "小(I) + 心(N) + 翼(N) + 翼(N)"),
        PhraseEntry(text: "在所难免", code: "drcq", type: 4, hint: "在(D) + 所(R) + 难(C) + 免(Q)"),
        PhraseEntry(text: "闪闪发光", code: "uuni", type: 4, hint: "闪(U) + 闪(U) + 发(N) + 光(I)"),
        PhraseEntry(text: "独一无二", code: "qgff", type: 4, hint: "独(Q) + 一(G) + 无(F) + 二(F)"),
        PhraseEntry(text: "全心全意", code: "wnwu", type: 4, hint: "全(W) + 心(N) + 全(W) + 意(U)"),
        PhraseEntry(text: "与时俱进", code: "gjwf", type: 4, hint: "与(G) + 时(J) + 俱(W) + 进(F)"),
        PhraseEntry(text: "香格里拉", code: "tsjr", type: 4, hint: "香(T) + 格(S) + 里(J) + 拉(R)"),
        PhraseEntry(text: "通货膨胀", code: "cwee", type: 4, hint: "通(C) + 货(W) + 膨(E) + 胀(E)"),
        PhraseEntry(text: "迫不及待", code: "rget", type: 4, hint: "迫(R) + 不(G) + 及(E) + 待(T)"),
        PhraseEntry(text: "他山之石", code: "wmpd", type: 4, hint: "他(W) + 山(M) + 之(P) + 石(D)"),
        PhraseEntry(text: "花花公子", code: "aawb", type: 4, hint: "花(A) + 花(A) + 公(W) + 子(B)"),
        PhraseEntry(text: "吃拿卡要", code: "kwhs", type: 4, hint: "吃(K) + 拿(W) + 卡(H) + 要(S)"),
        PhraseEntry(text: "随时随地", code: "bjbf", type: 4, hint: "随(B) + 时(J) + 随(B) + 地(F)"),
        PhraseEntry(text: "自然而然", code: "tqdq", type: 4, hint: "自(T) + 然(Q) + 而(D) + 然(Q)"),
        PhraseEntry(text: "脱颖而出", code: "exdb", type: 4, hint: "脱(E) + 颖(X) + 而(D) + 出(B)"),
    ]
}
